# Documentation regarding the Sheet API is available at https://myapiz.com/apis/sheet
#
name: Publish spreadsheet to SheetAPI
on:
  push:
    paths:
      - "*.xlsx"
    branches:
      - main
env:
  SHEET_API_KEY: ${{ secrets.SHEET_API_KEY }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - run: |
          # iterate over all xlsx files in the repository
          # and upload them to the SheetAPI
          for file in *.xlsx; do
            echo "Uploading $file"
            curl --data-binary @$file -XPOST  -H 'x-myapiz-key: ${SHEET_API_KEY}' 'https://api.myapiz.com/sheet/${file}'
          done
