# Documentation regarding the Sheet API is available at https://myapiz.com/apis/sheet
#
name: Publish spreadsheet to SheetAPI
on:
  push:
    #    paths:
    #  - "*.xlsx"
    #  - "tests/test_*.sh"
    branches:
      - main
env:
  SHEET_API_KEY: ${{ secrets.SHEET_API_KEY }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - run: |
          bash .github/workflows/publish.sh
      - run: |
          bash tests/test_mortgage.sh
